# -*- coding: utf-8 -*-
"""google playstore cleaning data

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MyyAWURX0G4Ti7drYyIYhULKMDIgs8kj
"""

import pandas as pd

import numpy as np

data = pd.read_csv('/content/googleplaystore.csv')

data.info()

data.nunique()

data.describe(include="all")

#rating
data.rating = data["Rating"].astype(float)
data.rating

#checking if there are any null values

(data.Rating.isna().sum(),"null values out of", len(data.Rating))

#review
data.Reviews.str.isnumeric()

#here it seems like the row is shifted
data[~data.Reviews.str.isnumeric()]

#dropping row 10472
data=data.drop(data.index[10472])

#just to confirm if its deleted
data[10471:].head(2)

data.Size=data.Size.str.replace('k','')
data.Size=data.Size.str.replace('M','e+3')
data.Size.head()

def is_convertable(v):
    try:
        float(v)
        return True
    except ValueError:
        return False
    
temp=data.Size.apply(lambda x: is_convertable(x))
temp.head()

data.Size[~temp].value_counts()

data.Size=data.Size.replace('Varies with device',np.nan)
data.Size=data.Size.replace('1,000+',1000)

data.Size=pd.to_numeric(data.Size)

#install
data.Installs.value_counts()

#aim is to convert all into integer
data.Installs = data.Installs.apply(lambda x: x.replace('+', ''))
data.Installs = data.Installs.apply(lambda x: x.replace(',',''))

#Type
#checking unique value here
#string here no need to change
data.Type.value_counts()

#price
data.Price=data.Price.apply(lambda x: x.replace('$', ''))

data.nunique()

#content rating
data['Content Rating'].unique()

#category
data['Category'].unique()

del data["Genres"]

del data["Current Ver"]

del data["Android Ver"]

del data["Last Updated"]

new_data = data.drop_duplicates()
new_data